name: example_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0-104.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.3.4
  get: 4.6.1
  google_fonts: ^2.3.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
