// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0qyVGLK2q9EH_TW2BOywGITRjW28bKDQ',
    appId: '1:849019469590:android:402bc59d03950d0b0d9a37',
    messagingSenderId: '849019469590',
    projectId: 'flutterfire-getcli-example',
    storageBucket: 'flutterfire-getcli-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNS1JUTdfPFZZ-AmbBU5o89jZBrx5uhg',
    appId: '1:849019469590:ios:d874073d7de281020d9a37',
    messagingSenderId: '849019469590',
    projectId: 'flutterfire-getcli-example',
    storageBucket: 'flutterfire-getcli-example.appspot.com',
    iosClientId: '849019469590-mism1ccl1u6lchoicohm11sfev1osne8.apps.googleusercontent.com',
    iosBundleId: 'com.flutterfiregetcliexample.app',
  );
}
